### PR TITLE
Update constraints for the xibs

### PR DESCRIPTION
**Pull request by JGiola**
Hi, I've updated some of the constraints inside the various xibs:

1. In WhatsNew xib I've set the stack view to track the scroll view width and not the main view one to fix the landscape mode and I've set leading and trailing constraints to the main title to allow it to wrap on multiple lines. I've also removed an unnecessary view inside the the stack view for the main title.
2. In WhatsNewItemTextView xib I've update the only constraint that still track the superview directly and not the safe area
3. In WhatsNewItemImageView xib I've updated the title constrains to allow it to wrap on multiple lines and not be truncated at the first one

I've also a question, I've seen that the continue button is inside a subview that is not much of utility and that has a negative top distance to the scroll view. There is a reason for that or is some kind of drag error?

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Hey @JGiola, thanks for you contribution! All good points so I think it makes sense to merge this PR. I've only noticed a problem on the iPhone X in landscape. I think it's something related to the `safeArea` and not sure if it was present before. Could you please take a look? The `scrollView` has the wrong horizontal content size and can scroll horizontally (which shouldn't happen).

The "Continue" button is inside a subview to be always on top of the `scrollView` so that the user can skip the screen without scrolling at the bottom. The negative spacing is only there to make the content of the `scrollView` disappear a little bit before without touching the button.

**Comment by JGiola** [comment]
The scroll view width is fixed on 6116352, I've tested again and is working correctly, the stack view now has always the same width of the scroll view frame.

The button always on top of the scroll view content can be achieved even without a wrapping view, simply put it as the last item inside the storyboard (it's already), and with the actual constraints, the scroll view content is actually ending half a point after the button. Can I try to fix it? And if yes, how much do you prefer that the content will stop before reaching the button?

**Comment by BalestraPatrick** [comment]
@JGiola Sure, I think 2-3 pixels would suffice 👍

**Comment by JGiola** [comment]
I've updated the constraints. If I may, I kindly suggest to change the bottom button constraint to reduce it's constant value when in compact height configuration, so the scroll view can breath more in landscape orientation

**Comment by BalestraPatrick** [comment]
I think the scrolling issue on iPhone X is still there. Please see the attached screenshot.
simulator screen shot - iphone x - 2017-11-07 at 09 52 54

**Comment by JGiola** [comment]
🤔 very strange, what Xcode/Simulator version are you running the code? I've running Xcode 9.1 on all the iOS Simulator 11.1 and in landscape none of them are scrolling horizontally

**Comment by BalestraPatrick** [comment]
@JGiola I am also using Xcode 9.1 😟

**Comment by BalestraPatrick** [comment]
I see this was happening even before your PR, so I think we can merge this and create another issue to optimize the UI on landscape iPhone X. Thanks a lot for your contribution! 👍

**Pull request merged**
