### PR TITLE
Fix set properties before load view

### PR DESCRIPTION
**Pull request by nixzhu**

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Hey! I am not sure which problem you're trying to fix, could you please describe the issue? 
The `IBOutlet`s are declared as implicitly unwrapped optionals so they would crash anyway if you'd try to access them before loading the view.

**Comment by nixzhu** [comment]
Hi, we use WhatsNew via CocoaPods. The following code will cause a crash (We doesn’t use storyboard BTW):

        let whatsNew = WhatsNewViewController(items: items)
        //whatsNew.titleText = LocalizedString.titleWhatsNew
        //whatsNew.buttonText = LocalizedString.titleContinue
        whatsNew.presentIfNeeded(on: self)

The comment line codes will access IBOutlet in didSet, but the view is not loaded yet, so it will crash.

Maybe it’s a timing issue.

**Comment by BalestraPatrick** [comment]
@nixzhu Yes you're right, this fixes it!

**Comment by nixzhu** [comment]
@BalestraPatrick 😀 Could you update the pod?

**Comment by BalestraPatrick** [comment]
@nixzhu Now it's done!

**Pull request merged**
